language: minimal

services:
  - docker

branches:
  only:
    - master

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/proxy:$TRAVIS_BRANCH .
  - docker push $DOCKER_USERNAME/proxy:$TRAVIS_BRANCH