version: '3.1'

services:

  wordpress1:
    image: wordpress:latest
    restart: always
    ports:
      - 8001:80
    expose:
      - "8001"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: web01
    networks:
      - darkweb

  wordpress2:
    image: wordpress:latest
    restart: always
    ports:
      - 8002:80
    expose:
      - "8002"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: web02
    networks:
      - mainet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - darkweb
      - mainet
  nginx:
    build:
      context: .
      dockerfile: ./nginxDockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - darkweb
      - mainet

networks:
  darkweb:
  mainet:
