version: '3.6'

services:

  wordpress1:
    image: wordpress:${WORDPRESS_VERSION:-php7.3-fpm}
    container_name: wordpress1
    restart: always
    volumes:
      - ./wordpress1:/var/www/html
#    volumes:
#      - assetsVolume:/var/www/html/wp-content/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: web01
    networks:
      - darkweb

  wordpress2:
    image: wordpress:${WORDPRESS_VERSION:-php7.3-fpm}
    container_name: wordpress2
    restart: always
    volumes:
      - ./wordpress2:/var/www/html
#    volumes:
#      - assetsVolume:/var/www/html/wp-content/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: web02
    networks:
      - mainet

  db:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - darkweb
      - mainet

  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: proxy
    ports:
      - "80:80"
    restart: always
    networks:
      - darkweb
      - mainet

  nginx1:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx1
    # ports:
    #   - '80:80'
    volumes:
      - ${NGINX_CONF_DIR:-./nginx1}:/etc/nginx/conf.d
      - ${WORDPRESS_DATA_DIR:-./wordpress2}:/var/www/html
    depends_on:
      - wordpress2
    restart: always
    ports:
      - 8002:80
    networks:
      - darkweb
      - mainet

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    # ports:
    #   - '80:80'
    volumes:
      - ${NGINX_CONF_DIR:-./nginx}:/etc/nginx/conf.d
      - ${WORDPRESS_DATA_DIR:-./wordpress1}:/var/www/html
    depends_on:
      - wordpress1
    restart: always
    ports:
      - 8001:80
    networks:
      - darkweb
      - mainet

networks:
  darkweb:
  mainet:

#volumes:
#  assetsVolume:
#    driver: local-persist
#    driver_opts:
#      mountpoint: /home/super-waddle/assets
