version: '3.6'

services:

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    restart: always
    volumes:
    - uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#    volumes:
#      - assetsVolume:/var/www/html/wp-content/
    ports:
      - 8001:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: web01
    networks:
      - darkweb

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    restart: always
#    volumes:
#      - assetsVolume:/var/www/html/wp-content/
    ports:
      - 8002:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: web02
    networks:
      - mainet

  db:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - darkweb
      - mainet
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: proxy
    ports:
      - "80:80"
    restart: always
    networks:
      - darkweb
      - mainet

networks:
  darkweb:
  mainet:

#volumes:
#  assetsVolume:
#    driver: local-persist
#    driver_opts:
#      mountpoint: /home/super-waddle/assets
