version: '3'

services:

  wordpress1:
    image: wordpress:latest
    restart: always
    ports:
      - 8001:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: web01
    networks:
      - darkweb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  wordpress2:
    image: wordpress:latest
    restart: always
    ports:
      - 8002:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: web02
    networks:
      - mainet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - darkweb
      - mainet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: superwaddle/proxy:master
    ports:
      - "80:80"
    restart: always
    networks:
      - darkweb
      - mainet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  darkweb:
  mainet: