version: '3'

services:
  web01:
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8000:80"